### ISSUE TITLE
linux

### ISSUE THREAD

**Issue by ZorbakScape** [AustinMay1/JagexLauncher-HDOS#1]
just to be sure this is for linux right?

**Comment by AustinMay1** [comment]
@ZorbakScape yes, linux. This doesn't automatically install the client though. You'll need to install it manually through flatpak afterwards. I made this before TormStorm made the changes though so his might be better to use but still requires manual installation of the client. https://github.com/TormStorm/jagex-launcher-linux

**Comment by ZorbakScape** [comment]
Awesome i only need directories tbh as im making a client switcher and my pc doesn't have enough ram to run a Linux vm so thank you for making this
